Service:
  name: user_service
  port: 50051
  timeout: 5
Database:

EndPoints:
  post_login: https://bootcamper.dipanshu.work/api/v1/auth/login
  get_bootcamps: https://bootcamper.dipanshu.work/api/v1/bootcamps
  post_bootcamp: https://bootcamper.dipanshu.work/api/v1/bootcamps
