kind: Deployment
apiVersion: apps/v1
metadata:
  name: bootcamp-service
  labels:
    service: bootcamp-service
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      service: bootcamp-service
  template:
    metadata:
      name: bootcamp-service
      labels:
        service: bootcamp-service
    spec:
      containers:
        - name: bootcamp-service
          image: dipanshuchaubey/bootcamp-service:latest
          imagePullPolicy: Always
          env:
            - name: ENV
              value: "dev"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=bootcamp-service,service.version=1.4"
          ports:
            - containerPort: 50051
              name: bootcamp-svc
          volumeMounts:
            - name: bootcamp-service-secret
              mountPath: /app/secrets
              subPath: bootcamp_api.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "250m"
      volumes:
        - name: bootcamp-service-secret
          secret:
            secretName: bootcamp-service-secret
---
kind: Service
apiVersion: v1
metadata:
  name: bootcamp-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
      name: bootcamp-service-service
  selector:
    service: bootcamp-service
  type: ClusterIP
