kind: Deployment
apiVersion: apps/v1
metadata:
  name: bootcamp-service
  labels:
    service: bootcamp-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: bootcamp-service
  template:
    metadata:
      name: bootcamp-service
      labels:
        service: bootcamp-service
    spec:
      containers:
        - name: bootcamp-service
          image: dipanshuchaubey/bootcamp-service:latest
          imagePullPolicy: Always
          env:
            - name: ENV
              value: "dev"
          ports:
            - containerPort: 50051
              name: bootcamp-svc
---
kind: Service
apiVersion: v1
metadata:
  name: bootcamp-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
      name: bootcamp-service-service
  selector:
    service: bootcamp-service
  type: ClusterIP
